server:
  port: 82
  max-http-header-size: 65536
spring:
  profiles:
    active: prd
  application:
    name: health-consumer-server

  # 限制文件上传大小
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
      enabled: true
      file-size-threshold: 0
  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms


# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/	#注册中心url
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/	#注册中心url
    fetch-registry: true
    register-with-eureka: false


