# 日志配置
logging:
  # 日志级别
  level:
    com:
      tian: info
  file:
    # 日志文件名格式
    name: D:\log\health-job.txt
  logback:
    rollingpolicy:
      # 最大日志文件大小(默认为10MB)
      max-file-size: 30MB
      # 要保留的日志备份的总大小(默认为0B)
      total-size-cap: 1GB
      # 保存存档日志文件的最大天数(默认为7天)
      max-history: 30
      # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
      file-name-pattern: /logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz
  pattern:
    # 日志记录格式[组件名称] [时间戳] [日志级别] [类名.方法名] [消息文本]
    file: healthJob %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n

